include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**.g.dart"
    - "**.freezed.dart"

linter:
  rules:
    always_use_package_imports: true
    avoid_slow_async_io: true
    prefer_final_fields: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    prefer_final_parameters: true
    prefer_relative_imports: false
    sort_unnamed_constructors_first: true
    sort_constructors_first: true
    use_key_in_widget_constructors: false