name: geldwegwijzer
description: An app for helping people pay with cash.

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  intl: ^0.19.0
  localstorage: ^4.0.1+4
  package_info: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
   - assets/
   - assets/euros/
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/Open_Sans/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/Open_Sans/OpenSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Open_Sans/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/Open_Sans/OpenSans-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Open_Sans/OpenSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/Open_Sans/OpenSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Open_Sans/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Open_Sans/OpenSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Open_Sans/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/Open_Sans/OpenSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Open_Sans/OpenSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Open_Sans/OpenSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic